### ISSUE TITLE
unable to install it

### ISSUE THREAD

**Issue by jstrebel** [jaluebbe/GPSTracker#5]
Hi, my apology to bother you.

I tried to install the repositories on Raspberry "bullseye" I am not sure is this the version I should use.
The first script produces a error message "-bash: python3-pip: command not found"
If I check pip3 
$ pip3 -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9) pip3 seems to exist.

UPDATE: habe etwas weiter gemacht: (python3-pip ersetzt durch pip3) und git installiert
nächster Versuch: 
kobi@gpslogger:~ $ sudo pip3 git python3-smbus python3-gps  # optional: chrony gpsd-clients
ERROR: unknown command "git"
end update //
sudo pip3 git python3-smbus python3-gps  # optional: chrony gpsd-clients
Thanks Jakob

The second script stops almost immediately.
below are the console outputs:
kobi@gpslogger:~ $ sudo apt-get install redis-server gpsd
python3-pip git python3-smbus python3-gps  # optional: chrony gpsd-clients
sudo pip3 install PyGeodesy fastapi uvicorn redis geojson ahrs \
aioredis==2 numpy websockets
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gpsd is already the newest version (3.22-4).
redis-server is already the newest version (5:6.0.16-1+deb11u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-bash: python3-pip: command not found
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyGeodesy
  Downloading https://www.piwheels.org/simple/pygeodesy/PyGeodesy-22.7.2-py3-none-any.whl (801 kB)
    
Collecting fastapi
  Downloading https://www.piwheels.org/simple/fastapi/fastapi-0.78.0-py3-none-any.whl (54 kB)
  
Collecting uvicorn
  Downloading uvicorn-0.18.2-py3-none-any.whl (57 kB)
   
Collecting redis
  Downloading redis-4.3.4-py3-none-any.whl (246 kB)
Collecting geojson
  Downloading https://www.piwheels.org/simple/geojson/geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Collecting ahrs
  Downloading AHRS-0.3.1-py3-none-any.whl (197 kB)
Collecting aioredis==2
  Downloading https://www.piwheels.org/simple/aioredis/aioredis-2.0.0-py3-none-any.whl (69 kB)
 Collecting numpy
  Downloading numpy-1.23.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.9 MB)
 Collecting websockets
  Downloading websockets-10.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (106 kB)
 Collecting typing-extensions
  Downloading https://www.piwheels.org/simple/typing-extensions/typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting async-timeout
  Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2
  Downloading pydantic-1.9.1-py3-none-any.whl (142 kB)
Collecting starlette==0.19.1
  Downloading https://www.piwheels.org/simple/starlette/starlette-0.19.1-py3-none-any.whl (63 kB) 
Collecting anyio<5,>=3.4.0
  Downloading https://www.piwheels.org/simple/anyio/anyio-3.6.1-py3-none-any.whl (80 kB)  
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<5,>=3.4.0->starlette==0.19.1->fastapi) (2.10)
Collecting sniffio>=1.1
  Downloading https://www.piwheels.org/simple/sniffio/sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting deprecated>=1.2.3
  Downloading https://www.piwheels.org/simple/deprecated/Deprecated-1.2.13-py2.py3-none-any.whl (9.5 kB)
Collecting packaging>=20.4
  Downloading https://www.piwheels.org/simple/packaging/packaging-21.3-py3-none-any.whl (40 kB)   
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (77 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading https://www.piwheels.org/simple/pyparsing/pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting click>=7.0
  Downloading https://www.piwheels.org/simple/click/click-8.1.3-py3-none-any.whl (96 kB)
Collecting h11>=0.8
  Downloading https://www.piwheels.org/simple/h11/h11-0.13.0-py3-none-any.whl (58 kB)
Installing collected packages: sniffio, wrapt, typing-extensions, pyparsing, anyio, starlette, pydantic, packaging, numpy, h11, deprecated, click, async-timeout, websockets, uvicorn, redis, PyGeodesy, geojson, fastapi, aioredis, ahrs
Successfully installed PyGeodesy-22.7.2 ahrs-0.3.1 aioredis-2.0.0 anyio-3.6.1 async-timeout-4.0.2 click-8.1.3 deprecated-1.2.13 fastapi-0.78.0 geojson-2.5.0 h11-0.13.0 numpy-1.23.0 packaging-21.3 pydantic-1.9.1 pyparsing-3.0.9 redis-4.3.4 sniffio-1.2.0 starlette-0.19.1 typing-extensions-4.3.0 uvicorn-0.18.2 websockets-10.3 wrapt-1.14.1
kobi@gpslogger:~ $ 
kobi@gpslogger:~ $ sudo cp etc/systemd/system/button_shutdown.service /etc/systemd/system/
chmod +x /home/pi/GPSTracker/gps_tracker/button_shutdown.py
sudo systemctl enable button_shutdown.service
cp: cannot stat 'etc/systemd/system/button_shutdown.service': No such file or directory
chmod: cannot access '/home/pi/GPSTracker/gps_tracker/button_shutdown.py': No such file or directory
Failed to enable unit: Unit file button_shutdown.service does not exist.

**Comment by jaluebbe** [comment]
Hi Jakob,
there is an important change in the recent Raspberry Pi OS version: It enforces to select a username, in your case "kobi". My setup is still based on the old standard that the user is called "pi" by default. It's on my TODO list to find a solution for this. You may either do a fresh start with user "pi" or replace the patterns "User=pi" and "/home/pi" in all files with your chosen username. 
And sorry for a missing line continuation character in the begin of my installation instruction.

**Comment by jaluebbe** [comment]
The installation instructions are updated to fit to the current release of Raspberry Pi OS.
